

export const SET_ORDER_SHIPPING = "SET_ORDER_SHIPPING"
export const SET_CACHE_RATE = "SET_CACHE_RATE"

export const SAVE_QUERY_ORDERS = "SAVE_QUERY_ORDERS"
export const SET_QUERY_STATUS_ERROR = "SET_QUERY_STATUS_ERROR"
export const UPDATE_QUERY = "UPDATE_QUERY"

//New . . .
//Order Cache...
export const SET_CURRENT_PM_ORDER = "SET_CURRENT_PM_ORDER"
export const SET_CURRENT_SHIPSTATION_ORDER = "SET_CURRENT_SHIPSTATION_ORDER"
export const SET_CURRENT_PM_ORDER_AND_SHIPSTATION_ORDER = "SET_CURRENT_PM_ORDER_AND_SHIPSTATION_ORDER"
export const RESET_CURRENT_PM_ORDER = "RESET_CURRENT_PM_ORDER"
export const RESET_CURRENT_SHIPSTATION_ORDER = "RESET_CURRENT_SHIPSTATION_ORDER"
export const RESET_CURRENTS = "RESET_CURRENTS"

//Romaneos...
export const ADD_ROMANEO_TO_LIST_PRINT = "ADD_ROMANEO_TO_LIST_PRINT"
export const CLEAN_ROMANEO_LIST = "CLEAN_ROMANEO_LIST"

//Config...
export const UPDATE_CONFIG_OPTIONS_SERVICES = "UPDATE_CONFIG_OPTIONS_SERVICES"
export const UPDATE_CONFIG_OPTIONS_TAGLOCATION = "UPDATE_CONFIG_OPTIONS_TAGLOCATION"
export const UPDATE_CONFIG_OPTIONS_FRONTEND = "UPDATE_CONFIG_OPTIONS_FRONTEND"

//Navigarion...
export const SET_ORDER_PAGE = "SET_ORDER_PAGE"
export const SET_ORDER_EDITING_PM_ORDER_PAGE = "SET_ORDER_EDITING_PM_ORDER_PAGE"
export const RESET_ORDER_PAGE = "RESET_ORDER_PAGE"
